# Build stage
FROM golang:alpine AS builder

WORKDIR /app

# Загружаем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем минимальный бинарник для парсера
RUN CGO_ENABLED=0 GOOS=linux go build -o scraper ./cmd/scraper

# Production stage
FROM alpine:latest
RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

# Копируем готовый бинарник из стадии сборки
COPY --from=builder /app/scraper .

# Запускаем скрипт-дэмон
CMD ["./scraper"]
